query AdminProductionCount($status: String!) {
  productions(status: $status) {
    edges {
      node {
        id
        name
        slug
        society {
          id
          name
        }
      }
    }
  }
}
