fragment ProductionBasicInfo on ProductionNode {
  id
  name
  subtitle
  description
  contactEmail
  society {
    id
    name
    slug
    logo {
      id
      url
    }
  }
  featuredImage {
    id
    url
  }
  status
  ageRating
  slug
  start
  end
  minSeatPrice
  contentWarnings {
    information
    warning {
      shortDescription
      longDescription
    }
  }
  isBookable
}
