fragment ProductionPerformances on ProductionNode {
  performances {
    edges {
      node {
        id
        venue {
          id
          name
          slug
        }
        disabled
        doorsOpen
        start
        end
        durationMins
        soldOut
        isInperson
        isOnline
      }
    }
  }
}
