fragment ProductionBasicInfo on ProductionNode {
  id
  name
  subtitle
  description
  society {
    name
    slug
    logo {
      url
    }
  }
  featuredImage {
    url
  }
  ageRating
  slug
  start
  end
  minSeatPrice
  warnings {
    description
  }
  isBookable
}
