import type { CodegenConfig } from '@graphql-codegen/cli';
import publicConfig from './config.public';
require('dotenv').config();

const config: CodegenConfig = {
  overwrite: true,
  schema: process.env.GQL_SCHEMA ?? publicConfig().api.graphqlEndpointInternal,
  documents: './graphql/**/*.(gql|graphql)',
  generates: {
    // We cheat a bit here by relying on codegen to generate us base types
    // Since @graphql-codegen/typescript-operations v6, these are no longer generated by default
    // They are now instead in a separate file, which we can import into our operations types for legacy support
    './graphql/codegen/base-types.generated.ts': {
      plugins: ['typescript'],
      config: {
        vueCompositionApiImportFrom: 'vue',
        scalars: {
          IdInputField: 'string',
          Date: 'any',
          DateTime: 'any',
          GenericScalar: 'any'
        }
      }
    },
    './graphql/codegen/operations.generated.ts': {
      plugins: ['typescript-operations', 'typescript-vue-apollo'],
      config: {
        vueCompositionApiImportFrom: 'vue',
        scalars: {
          IdInputField: 'string',
          Date: 'any',
          DateTime: 'any',
          GenericScalar: 'any'
        },
        importSchemaTypesFrom: './graphql/codegen/base-types.generated.ts'
      }
    }
  }
};

export default config;
