fragment PerformanceTicketOptions on PerformanceSeatGroupNode {
  id
  capacityRemaining
  price
  seatGroup {
    id
    name
    description
    capacity
  }
  concessionTypes {
    concessionType {
      id
      name
      description
    }
    price
  }
}
