query adminProductionShow($slug: String!) {
  production(slug: $slug) {
    id
    name
    subtitle
    society {
      name
    }
    status {
      description
    }
    slug
    start
    end
    isBookable
  }
}
