#import "../fragments/production/ProductionBasicInfoFragment.gql"
#import "../fragments/production/ProductionPerformancesFragment.gql"
#import "../fragments/performance/PerformanceTicketOptionsFragment.gql"
query fullPerformanceAndTicketOptions($id: ID!) {
  performance(id: $id) {
    id
    capacityRemaining
    venue {
      id
      name
      slug
    }
    disabled
    doorsOpen
    start
    end
    durationMins
    soldOut
    isInperson
    isOnline
    production {
      id
      ...ProductionBasicInfo
      ...ProductionPerformances
    }
    capacityRemaining
    discounts {
      edges {
        node {
          id
          name
          seatGroup {
            id
            name
          }
          requirements {
            number
            concessionType {
              id
              name
            }
          }
        }
      }
    }
    ticketOptions {
      ...PerformanceTicketOptionsFragment
    }
  }
}
