#import "../fragments/production/ProductionBasicInfoFragment.gql"
#import "../fragments/production/ProductionPerformancesFragment.gql"
query performanceTicketOptions($id: ID!) {
  performance(id: $id) {
    id
    capacityRemaining
    venue {
      name
      slug
    }
    disabled
    doorsOpen
    start
    end
    durationMins
    soldOut
    isInperson
    isOnline
    production {
      ...ProductionBasicInfo
      ...ProductionPerformances
    }
    capacityRemaining
    discounts {
      name
      seatGroup {
        id
        name
      }
      requirements {
        number
        concessionType {
          id
          name
        }
      }
    }
    ticketOptions {
      capacityRemaining
      seatGroup {
        id
        name
        description
      }
      concessionTypes {
        concessionType {
          id
          name
          description
        }
        price
      }
    }
  }
}
