query upcomingProductions($now: DateTime) {
  productions(first: 5, orderBy: "start", end_Gte: $now, status: "PUBLISHED") {
    edges {
      node {
        id
        name
        slug
        subtitle
        description
        featuredImage {
          id
          url
        }
        coverImage {
          id
          url
        }
        society {
          id
          name
          slug
        }
        start
        end
      }
    }
  }
}
