query productionBySlug($slug: String!) {
  production(slug: $slug) {
    id
    name
    id
    subtitle
    description
    society {
      id
      name
      slug
      logo {
        url
      }
    }
    posterImage {
      url
    }
    featuredImage {
      url
    }
    coverImage {
      url
    }
    ageRating
    facebookEvent
    slug
    start
    end
    minSeatPrice
    warnings {
      description
    }
    performances(orderBy: "start", disabled: false) {
      edges {
        node {
          id
          venue {
            id
            name
            slug
            publiclyListed
          }
          doorsOpen
          isBookable
          start
          end
          soldOut
          durationMins
          isOnline
          isInperson
          ticketsBreakdown {
            totalCapacity
          }
        }
      }
    }
    isBookable
    crew {
      name
      role {
        department {
          description
        }
      }
    }
    cast {
      name
      role
      profilePicture {
        url
      }
    }
    productionTeam {
      name
      role
    }
  }
}
