query productionBySlug($slug: String!) {
  production(slug: $slug) {
    id
    name
    status
    subtitle
    description
    contactEmail
    society {
      id
      name
      slug
      logo {
        id
        url
      }
    }
    posterImage {
      id
      url
    }
    featuredImage {
      id
      url
    }
    coverImage {
      id
      url
    }
    ageRating
    facebookEvent
    slug
    start
    end
    minSeatPrice
    contentWarnings {
      information
      warning {
        id
        shortDescription
        longDescription
      }
    }
    productionAlert
    performances(orderBy: "start", disabled: false) {
      edges {
        node {
          id
          venue {
            id
            name
            slug
            publiclyListed
          }
          doorsOpen
          isBookable
          start
          end
          soldOut
          durationMins
          intervalDurationMins
          isOnline
          isInperson
          isRelaxed
          relaxedName
          relaxedCategories {
            id
            shortDescription
            longDescription
          }
          ticketsBreakdown {
            totalCapacity
          }
        }
      }
    }
    isBookable
    crew {
      name
      role {
        department
      }
    }
    cast {
      name
      role
      profilePicture {
        url
      }
    }
    productionTeam {
      name
      role
    }
  }
}
