query relaxedCategories {
  relaxedCategories {
    edges {
      node {
        id
        shortDescription
        longDescription
        helpText
        defaultRelaxed
        defaultSensoryFriendly
      }
    }
  }
}
