query society($slug: String!) {
  society(slug: $slug) {
    name
    id
    description
    slug
    logo {
      url
    }
    banner {
      url
    }
    website
    contact
    productions(orderBy: "start", first: 4) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        node {
          id
          name
          end
          isBookable
          slug
        }
      }
    }
  }
}
