query upcomingProductions($now: DateTime, $afterCursor: String) {
  productions(
    first: 9
    orderBy: "start"
    after: $afterCursor
    end_Gte: $now
    status: PUBLISHED
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        name
        slug
        featuredImage {
          id
          url
        }
        start
        end
        isBookable
      }
    }
  }
}
