query upcomingProductions($now: DateTime, $afterCursor: String) {
  productions(first: 9, orderBy: "start", after: $afterCursor, end_Gte: $now) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        name
        slug
        featuredImage {
          url
        }
        start
        end
      }
    }
  }
}
