query upcomingSiteMessages(
  $now: DateTime
  $afterCursor: String
  $displayLocation: String
) {
  siteMessages(
    first: 5
    orderBy: "display_start"
    after: $afterCursor
    displayStart_Lte: $now
    end_Gte: $now
    displayLocation: $displayLocation
  ) {
    pageInfo {
      hasNextPage
      endCursor
    }
    edges {
      node {
        id
        message
        active
        indefiniteOverride
        displayStart
        eventStart
        eventEnd
        eventDuration
        creator {
          id
          firstName
          lastName
        }
        type
        dismissalPolicy
        toDisplay
      }
    }
  }
}
