#import "../fragments/booking/BookingWithProductionDetails.gql"
query userCompletedBooking($bookingRef: String!) {
  me {
    bookings(reference: $bookingRef, statusIn: ["PAID", "CANCELLED"]) {
      edges {
        node {
          ...BookingWithProductionDetails
        }
      }
    }
  }
}
