#import "../fragments/booking/BookingWithProductionDetails.gql"
query userPaidBooking($bookingRef: String!) {
  me {
    bookings(reference: $bookingRef, status: "PAID") {
      edges {
        node {
          ...BookingWithProductionDetails
        }
      }
    }
  }
}
