export default {
  solid: [
    'faArrowRight',
    'faBuilding',
    'faChevronDown',
    'faChevronLeft',
    'faChevronRight',
    'faChevronUp',
    'faCircleNotch',
    'faClock',
    'faInfoCircle',
    'faLink',
    'faMapMarkedAlt',
    'faMoneyCheckAlt',
    'faMoneyBill',
    'faSignInAlt',
    'faTheaterMasks',
    'faTicketAlt',
    'faTimesCircle',
    'faUserEdit',
    'faClipboardList',
    'faCashRegister',
    'faUserCheck',
    'faCalendar',
    'faSquare',
    'faCheckSquare',
    'faSearch',
    'faSort',
    'faSortUp',
    'faSortDown',
    'faCheck',
    'faTimes',
    'faExclamation',
  ],
  brands: ['faFacebook'],
}
