query adminProductionShow($slug: String!) {
  production(slug: $slug) {
    id
    name
    subtitle
    society {
      name
    }
    status {
      description
      value
    }
    slug
    start
    end
    isBookable
    salesBreakdown {
      totalSales
      totalCardSales
      providerPaymentValue
      appPaymentValue
      societyTransferValue
      societyRevenue
    }
    totalCapacity
    totalTicketsSold
  }
}
