#import "../../../fragments/booking/BookingWithProductionDetails.gql"
query adminBookingDetail($bookingReference: String!) {
  bookings(reference: $bookingReference) {
    edges {
      node {
        ...BookingWithProductionDetails
        createdAt
        updatedAt
        creator {
          id
          firstName
          lastName
          email
        }
        adminDiscountPercentage
        user {
          id
          firstName
          lastName
          email
        }
      }
    }
  }
}
