query adminProductionEdit($slug: String!) {
  production(slug: $slug) {
    id
    name
    subtitle
    contactEmail
    society {
      id
      name
      logo {
        id
        url
      }
    }
    slug
    description
    excerptText
    contentWarnings {
      information
      warning {
        id
        shortDescription
        longDescription
      }
    }
    coverImage {
      id
      url
    }
    featuredImage {
      id
      url
    }
    posterImage {
      id
      url
    }
    ageRating
    facebookEvent
    performances(orderBy: "start") {
      edges {
        node {
          id
          venue {
            id
            name
          }
          doorsOpen
          start
          soldOut
          isOnline
          isInperson
        }
      }
    }
    isBookable
  }
}
