query adminProductionShow($slug: String!) {
  production(slug: $slug) {
    id
    name
    subtitle
    society {
      id
      name
    }
    status
    slug
    start
    end
    isBookable
    salesBreakdown {
      netIncome
      totalSales
      totalCardSales
      providerPaymentValue
      appPaymentValue
      societyTransferValue
      societyRevenue
    }
    totalCapacity
    totalTicketsSold
    permissions
  }
}
