#import "../../../fragments/performance/PerformanceTicketOptionsFragment.gql"
query adminPerformanceDetail($productionSlug: String!, $performanceId: ID!) {
  production(slug: $productionSlug) {
    id
    slug
    name
    permissions
    performances(id: $performanceId) {
      edges {
        node {
          id
          venue {
            id
            name
            slug
            internalCapacity
          }
          description
          disabled
          doorsOpen
          start
          end
          durationMins
          intervalDurationMins
          soldOut
          isOnline
          isInperson
          isBookable
          capacity
          capacityRemaining

          ticketOptions {
            ...PerformanceTicketOptionsFragment
            capacity
            numberTicketsSold
          }
          ticketsBreakdown {
            totalCapacity
            totalTicketsSold
          }
          salesBreakdown {
            societyRevenue
          }

          discounts {
            edges {
              node {
                id
                percentage
                performances {
                  edges {
                    node {
                      id
                    }
                  }
                }
                seatGroup {
                  id
                  name
                  description
                }
                requirements {
                  id
                  number
                  concessionType {
                    id
                    name
                    description
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
