query adminProductions(
  $endGte: DateTime
  $offset: Int
  $status: String
  $startLte: DateTime
  $search: String
) {
  productions(
    first: 10
    orderBy: "-start"
    userHasPermission: "view_production"
    offset: $offset
    start_Lte: $startLte
    end_Gte: $endGte
    status: $status
    search: $search
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
        name
        slug
        featuredImage {
          id
          url
        }
        status {
          description
          value
        }
        society {
          id
          name
        }
        start
        end
        isBookable
      }
    }
  }
}
