#import "../../../fragments/booking/DetailedBookingDetails.gql"
query adminBookingLookup($reference: String!) {
  bookings(reference: $reference) {
    edges {
      node {
        ...DetailedBookingDetails
      }
    }
  }
}
