#import "../../../fragments/booking/BasicBookingDetails.gql"
query adminBookings(
  $offset: Int
  $status: String
  $productionSearch: String
  $userSearch: String
  $orderBy: String
) {
  bookings(
    first: 10
    offset: $offset
    status: $status
    productionSearch: $productionSearch
    orderBy: $orderBy
    search: $userSearch
    expired: false
  ) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        ...BasicBookingDetails
        createdAt
        creator {
          id
          firstName
          lastName
        }
      }
    }
  }
}
