query boxOfficePerformanceBooking(
  $performanceId: ID!
  $bookingId: ID
  $bookingReference: String
) {
  performance(id: $performanceId) {
    id
    bookings(id: $bookingId, reference: $bookingReference) {
      edges {
        node {
          id
          reference
          user {
            firstName
            lastName
          }
          tickets {
            id
            seatGroup {
              name
            }
            concessionType {
              name
            }
            checkedInAt
            checkedInBy {
              firstName
              lastName
            }
          }
        }
      }
    }
  }
}
