query boxOfficePerformanceBooking($performanceId: ID!, $bookingId: ID!) {
  performance(id: $performanceId) {
    id
    bookings(id: $bookingId) {
      edges {
        node {
          id
          reference
          user {
            firstName
            lastName
          }
          tickets {
            id
            seatGroup {
              name
            }
            concessionType {
              name
            }
            checkedInAt
            checkedInBy {
              firstName
              lastName
            }
          }
        }
      }
    }
  }
}
