#import "../../fragments/production/ProductionBasicInfoFragment.gql"
query boxOfficePerformance($id: ID!) {
  performance(id: $id) {
    id
    capacityRemaining
    venue {
      id
      name
      slug
    }
    disabled
    doorsOpen
    start
    end
    intervalDurationMins
    durationMins
    soldOut
    isInperson
    isOnline
    production {
      ...ProductionBasicInfo
      posterImage {
        url
      }
    }
  }
}
