query productionBySlug($slug: String!) {
  production(slug: $slug) {
    name
    subtitle
    description
    society {
      name
      slug
      logo {
        url
      }
    }
    posterImage {
      url
    }
    featuredImage {
      url
    }
    coverImage {
      url
    }
    ageRating
    facebookEvent
    slug
    start
    end
    minSeatPrice
    warnings {
      warning
    }
    performances {
      edges {
        node {
          venue {
            name
            slug
          }
          doorsOpen
          start
          end
          durationMins
          isOnline
          isInperson
        }
      }
    }
    isBookable
    crew {
      name
      role {
        department
      }
    }
    cast {
      name
      role
      profilePicture {
        url
      }
    }
    productionTeam {
      name
      role
    }
  }
}
