fragment BasicBookingDetails on BookingNode {
  id
  reference
  status {
    description
  }
  user {
    id
    firstName
    lastName
  }
  performance {
    id
    start
    end
    production {
      id
      name
      slug
    }
  }
  tickets {
    id
  }
}
