fragment BookingPaymentDetails on BookingNode {
  transactions {
    edges {
      node {
        id
        createdAt
        type
        provider
        value
        cardBrand
        last4
      }
    }
  }
}
