fragment BookingPaymentDetails on BookingNode {
  payments {
    edges {
      node {
        createdAt
        type {
          value
          description
        }
        provider {
          value
          description
        }
        value
        cardBrand
        last4
      }
    }
  }
}
