#import "./AllPriceBreakdown.gql"
fragment BookingWithProductionDetails on BookingNode {
  id
  reference
  status
  priceBreakdown {
    ...AllPriceBreakdown
  }
  tickets {
    id
    seatGroup {
      id
      name
    }
    concessionType {
      id
      name
    }
  }
  performance {
    id
    production {
      id
      name
      slug
      subtitle
      society {
        id
        name
        slug
        logo {
          id
          url
        }
      }
      featuredImage {
        id
        url
      }
    }
    start
    end
    doorsOpen
    durationMins
    intervalDurationMins
    isRelaxed
    relaxedName
    venue {
      id
      slug
    }
  }
  transactions {
    edges {
      node {
        id
        createdAt
        type
        providerName
        providerTransactionId
        providerFee
        value
        cardBrand
        last4
      }
    }
  }
}
