#import "./AllPriceBreakdown.gql"
fragment BookingWithProductionDetails on BookingNode {
  id
  reference
  status {
    description
  }
  priceBreakdown {
    ...AllPriceBreakdown
  }
  tickets {
    id
    seatGroup {
      id
      name
    }
    concessionType {
      id
      name
    }
  }
  performance {
    id
    production {
      id
      name
      slug
      subtitle
      society {
        id
        name
        slug
        logo {
          url
        }
      }
      featuredImage {
        url
      }
    }
    start
    end
    doorsOpen
    durationMins
    venue {
      id
      slug
    }
  }
  payments {
    edges {
      node {
        createdAt
        type {
          value
        }
        provider {
          value
          description
        }
        value
        cardBrand
        last4
      }
    }
  }
}
