#import "./AllPriceBreakdown.gql"
#import "./BookingTicketDetails.gql"
#import "./BookingPaymentDetails.gql"
fragment DetailedBookingDetails on BookingNode {
  id
  reference
  status {
    value
    description
  }
  user {
    id
    firstName
    lastName
  }
  priceBreakdown {
    ...AllPriceBreakdown
  }
  ...BookingTicketDetails
  ...BookingPaymentDetails
  performance {
    id
    production {
      id
      name
      slug
    }
    start
    end
    doorsOpen
    venue {
      id
      slug
    }
    durationMins
  }
}
