#import "./AllPriceBreakdown.gql"
fragment DetailedBookingDetails on BookingNode {
  id
  reference
  status {
    description
  }
  user {
    firstName
    lastName
  }
  priceBreakdown {
    ...AllPriceBreakdown
  }
  tickets {
    id
    seatGroup {
      id
      name
    }
    concessionType {
      id
      name
    }
    checkedIn
  }
  performance {
    id
    production {
      id
      name
      slug
    }
    start
    end
    doorsOpen
    venue {
      slug
    }
    durationMins
  }
}
