#import "./AllPriceBreakdown.gql"
fragment DetailedBookingDetails on BookingNode {
  id
  reference
  status {
    description
  }
  user {
    firstName
    lastName
  }
  priceBreakdown {
    ...AllPriceBreakdown
  }
  tickets {
    id
    seatGroup {
      id
      name
    }
    concessionType {
      id
      name
    }
    checkedIn
  }
  payments {
    edges {
      node {
        createdAt
        type {
          value
          description
        }
        provider {
          value
          description
        }
        value
        cardBrand
        last4
      }
    }
  }
  performance {
    id
    production {
      id
      name
      slug
    }
    start
    end
    doorsOpen
    venue {
      slug
    }
    durationMins
  }
}
