#import "../fragments/BookingFragments.gql"
query bookingByID($bookingId: ID!) {
  booking(id: $bookingId) {
    id
    bookingReference
    status
    priceBreakdown {
      ...AllPriceBreakdown
    }
    tickets {
      id
      seatGroup {
        id
        name
      }
      concessionType {
        id
        name
      }
    }
    performance {
      id
      production {
        id
        name
      }
      venue {
        slug
      }
    }
  }
}
