#import "../fragments/booking/DetailedBookingDetails.gql"
query userDraftBookingForPerformance($performanceID: ID!) {
  authUser {
    bookings(performance: $performanceID, status: INPROGRESS) {
      edges {
        node {
          ...DetailedBookingDetails
        }
      }
    }
  }
}
