#import "../fragments/booking/DetailedBookingDetails.gql"
query myAccountDetails {
  me {
    firstName
    lastName
    email
    bookings(status: "PAID") {
      edges {
        node {
          ...DetailedBookingDetails
        }
      }
    }
  }
}
