#import "../fragments/booking/DetailedBookingDetails.gql"
query userDraftBookingForPerformance {
  authUser {
    bookings(status: PAID) {
      edges {
        node {
          ...DetailedBookingDetails
        }
      }
    }
  }
}
