#import "../fragments/booking/BookingWithProductionDetails.gql"
query userPaidBookingForPerformance {
  authUser {
    bookings(status: PAID) {
      edges {
        node {
          ...BookingWithProductionDetails
        }
      }
    }
  }
}
