#import "../fragments/booking/BookingWithProductionDetails.gql"
query userPaidBooking($bookingId: ID!) {
  authUser {
    firstName
    lastName
    email
    bookings(id: $bookingId, status: PAID) {
      edges {
        node {
          ...BookingWithProductionDetails
        }
      }
    }
  }
}
