#import "../fragments/booking/BookingWithProductionDetails.gql"
query userPaidBooking($bookingId: ID!) {
  me {
    firstName
    lastName
    email
    bookings(id: $bookingId, status: "PAID") {
      edges {
        node {
          ...BookingWithProductionDetails
        }
      }
    }
  }
}
