#import "../../fragments/booking/BasicBookingDetails.gql"
query paidBookings(
  $afterCursor: String
  $active: Boolean
  $orderBy: String = "start"
  $offset: Int
  $max: Int = 10
) {
  me {
    bookings(
      status: "PAID"
      first: $max
      orderBy: $orderBy
      active: $active
      offset: $offset
      after: $afterCursor
    ) {
      pageInfo {
        hasNextPage
        startCursor
        endCursor
      }
      edges {
        node {
          ...BasicBookingDetails
        }
      }
    }
  }
}
