#import "../../fragments/AddressFragment.gql"
query venuePageDetails($slug: String!) {
  venue(slug: $slug) {
    name
    internalCapacity
    description
    accessibilityInfo
    image {
      url
    }
    address {
      ...AddressFields
    }
  }
}
