#import "../../fragments/AddressFragment.gql"
query venuePageDetails($slug: String!, $now: DateTime, $afterCursor: String) {
  venue(slug: $slug) {
    name
    internalCapacity
    description
    accessibilityInfo
    accessibilityShort
    email
    website
    image {
      url
    }
    address {
      ...AddressFields
    }
    productions(
      first: 9
      orderBy: "start"
      after: $afterCursor
      end_Gte: $now
      status: PUBLISHED
    ) {
      pageInfo {
        hasNextPage
        endCursor
      }
      edges {
        node {
          id
          name
          slug
          start
          end
          isBookable
          featuredImage {
            url
          }
          coverImage {
            url
          }
          society {
            name
          }
        }
      }
    }
  }
}
