query venueUpcomingProductions(
  $slug: String!
  $now: DateTime!
  $nowDate: Date
) {
  venue(slug: $slug) {
    id
    name
    productions(orderBy: "start", end_Gte: $now, status: "PUBLISHED") {
      edges {
        node {
          id
          slug
          name
          start
          end
          isBookable
          featuredImage {
            id
            url
          }
          coverImage {
            id
            url
          }
          performances(runOn: $nowDate) {
            edges {
              node {
                id
                doorsOpen
                start
                soldOut
                end
                venue {
                  id
                  name
                }
                production {
                  id
                  name
                  featuredImage {
                    url
                  }
                  alternativePerformances: performances(disabled: false) {
                    edges {
                      node {
                        id
                        doorsOpen
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
