name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: yarn
      name: Install Yarn Dependencies
      
    - run: yarn build
      name: Build Project
      
    - run: yarn test:unit
      name: Run Unit Tests
      
    - name: Run End-to-End Tests
      uses: cypress-io/github-action@v1
      with:
        start: yarn serve --mode=production
        wait-on: http://localhost:8080/
        config_file: cypress.json
        spec: "tests/e2e/**/*"
      env:
        CYPRESS_baseUrl: http://localhost:8080/
