query adminSocietiesIndex {
  societies(userHasPermission: "add_production") {
    edges {
      node {
        id
        name
        slug
        logo {
          id
          url
        }
        permissions
      }
    }
  }
}
